# Part 2: Data
The data were comprised of audience and critics opinions, actor, director, and studio information, as well as notable academy award nominations and winnings, for a random sample of 651 movies obtained from the IMDb [@Needham1990], Rotten Tomatoes [@Flixter], and BoxOfficeMojo websites [@Fritz2008].

## Data Sources
Launched in October 1990 by Col Needham, the Internet Movie Database (abbreviated IMDb) is an online database of film information, audience and critics ratings, plot summaries and reviews.  As of November 2017, the site contained over 4.6 million titles, 8.2 million personalities, and hosts 80 million registered users [@Needham1990].  Rotten Tomatoes.com, so named from the practice of audiences throwing rotten tomatoes when disapproving of a poor stage performance, was launched officially in April 2000 by Berkeley student, Senh Duong. It provides audience and critics ratings  for some 26 million users worldwide [@Flixter]. BoxOfficeMojo was founded in 1999 tracks box office information and publishes it on its site [@Fritz2008].

## Generalizability & Causality
The data were **randomly sampled** from available IMDb and Rotten Tomatoes website apis, and so the inference *should* be generalizable to the population. Since this was an observational study, random assignment was not performed, as such **causality is not indicated by this analysis**.

## Data Preprocessing
As a first step, five new categorical variables were added to the data set:  
1. feature_film: "yes" if title_type is "Feature Film", "no" otherwise  
2. drama: "yes" if genre is "Drama", "no" otherwise  
3. mpaa_rating_R: "yes" if mpaa_rating is "R", "no" otherwise  
4. oscar_season: "yes" if thtr_rel_month is October, November, or December, "no" otherwise  
5. summer_season: "yes" if thtr_rel_month is May, June, July, or August, "no" otherwise  

Next, television movies, considered out of scope of this analysis, were removed from the data set. A quantitative variable representing the log number of IMDb votes was created and variables out of scope for the modeling phase were removed.  The remaining variables in scope of this study are listed in `r kfigr::figr(label = "vars", prefix = TRUE, link = TRUE, type="Table")`.  

`r kfigr::figr(label = "vars", prefix = TRUE, link = TRUE, type="Table")`: Movie Dataset Variables 
```{r vars}
vars <- read.csv("../vignettes/figs_tables/vars.csv")
knitr::kable(vars, align = 'c') %>%
  kableExtra::kable_styling(bootstrap_options = c("hover", "condensed", "responsive"), full_width = T, position = "center") 
```


* * *
